/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 6.glb --transform
Files: 6.glb [4.54MB] > 6-transformed.glb [1.46MB] (68%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Area6({ showModel }) {
  const { nodes, materials } = useGLTF("/6-transformed.glb");

    const param = 'crack_6'

  return (
    <group dispose={null}>
      <mesh
          onClick={()=>showModel(param)}
        geometry={nodes.Tile_1008.geometry}
        material={materials.Material_0}
      >
          <meshPhongMaterial
              color={new THREE.Color(0xeeeeee)}
              shininess={0}
          />
      </mesh>

    </group>
  );
}

useGLTF.preload("/6-transformed.glb");
