/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 7.glb --transform
Files: 7.glb [4.54MB] > 7-transformed.glb [1.46MB] (68%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Area7({ showModel }) {
  const { nodes, materials } = useGLTF("/7-transformed.glb");

  const param = 'crack_7'

  return (
    <group dispose={null}>
      <mesh
          onClick={()=>showModel(param)}
        geometry={nodes.Tile_1009.geometry}
        material={materials.Material_0} >
          <meshPhongMaterial
              color={new THREE.Color(0xeeeeee)}
              shininess={0}
          />
      </mesh>
    </group>
  );
}

useGLTF.preload("/7-transformed.glb");
